#!bin/sh
mkdir -p mongodb_cluster_router01_db
mkdir -p mongodb_cluster_router01_config
mkdir -p mongodb_cluster_router02_db
mkdir -p mongodb_cluster_router02_config
mkdir -p mongodb_cluster_configsvr01_db
mkdir -p mongodb_cluster_configsvr01_config
mkdir -p mongodb_cluster_configsvr02_db
mkdir -p mongodb_cluster_configsvr02_config
mkdir -p mongodb_cluster_configsvr03_db
mkdir -p mongodb_cluster_configsvr03_config
mkdir -p mongodb_cluster_shard01_a_db
mkdir -p mongodb_cluster_shard01_a_config
mkdir -p mongodb_cluster_shard01_b_db
mkdir -p mongodb_cluster_shard01_b_config
mkdir -p mongodb_cluster_shard01_c_db
mkdir -p mongodb_cluster_shard01_c_config
mkdir -p mongodb_cluster_shard02_a_db
mkdir -p mongodb_cluster_shard02_a_config
mkdir -p mongodb_cluster_shard02_b_db
mkdir -p mongodb_cluster_shard02_b_config
mkdir -p mongodb_cluster_shard02_c_db
mkdir -p mongodb_cluster_shard02_c_config
mkdir -p mongodb_cluster_shard03_a_db
mkdir -p mongodb_cluster_shard03_a_config
mkdir -p mongodb_cluster_shard03_b_db
mkdir -p mongodb_cluster_shard03_b_config
mkdir -p mongodb_cluster_shard03_c_db
mkdir -p mongodb_cluster_shard03_c_config
